
name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run-ui-tests:
    runs-on: macos-13   
    steps:
      - uses: actions/checkout@v3

      - name: Enable automation mode
        run: |
          automationmodetool
          automationmodetool enable-automationmode-without-authentication

      - name: Run UI Tests
        if: always()
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.3.app
          xcodebuild \
            test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -target "TestGHRunner" \
            -scheme "TestGHRunner" \
            -destination "platform=macOS"
